services:
  dev:
    container_name: is-dev
    build: src
    volumes:
      - "./src:/usr/src/app"
    depends_on:
      - database
    network_mode: host

  database:
    container_name: is-db
    build: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data: